-- MySQL Script generated by MySQL Workbench
-- Sun Jan  3 17:39:15 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema brewDay
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema brewDay
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `brewDay` DEFAULT CHARACTER SET utf8 ;
USE `brewDay` ;

-- -----------------------------------------------------
-- Table `brewDay`.`ingrediente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brewDay`.`ingrediente` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `disponibilita` FLOAT NOT NULL,
  `unitaMisura` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `brewDay`.`equipaggiamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brewDay`.`equipaggiamento` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `capacita` FLOAT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `brewDay`.`ricetta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brewDay`.`ricetta` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `descrizione` TEXT(2000) NOT NULL,
  `tempo_preparazione` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `brewDay`.`lotto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brewDay`.`lotto` (
  `id` INT NOT NULL,
  `commento` TEXT(2000) NOT NULL,
  `data` DATE NOT NULL,
  `valutazione` INT NULL,
  `equipaggiamento_id` INT NOT NULL,
  `ricetta_id` INT NOT NULL,
  `quantitaProdotta` FLOAT NOT NULL,
  PRIMARY KEY (`id`, `equipaggiamento_id`, `ricetta_id`),
  INDEX `fk_lotto_equipaggiamento1_idx` (`equipaggiamento_id` ASC) VISIBLE,
  INDEX `fk_lotto_ricetta1_idx` (`ricetta_id` ASC) VISIBLE,
  CONSTRAINT `fk_lotto_equipaggiamento1`
    FOREIGN KEY (`equipaggiamento_id`)
    REFERENCES `brewDay`.`equipaggiamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lotto_ricetta1`
    FOREIGN KEY (`ricetta_id`)
    REFERENCES `brewDay`.`ricetta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `brewDay`.`quantita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `brewDay`.`quantita` (
  `ingrediente_id` INT NOT NULL,
  `ricetta_id` INT NOT NULL,
  `quantita_necessaria` FLOAT NOT NULL,
  PRIMARY KEY (`ingrediente_id`, `ricetta_id`),
  INDEX `fk_ingrediente_has_ricetta_ricetta1_idx` (`ricetta_id` ASC) VISIBLE,
  INDEX `fk_ingrediente_has_ricetta_ingrediente_idx` (`ingrediente_id` ASC) VISIBLE,
  CONSTRAINT `fk_ingrediente_has_ricetta_ingrediente`
    FOREIGN KEY (`ingrediente_id`)
    REFERENCES `brewDay`.`ingrediente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ingrediente_has_ricetta_ricetta1`
    FOREIGN KEY (`ricetta_id`)
    REFERENCES `brewDay`.`ricetta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
